spring.application.name=SpringAIEmbedding
server.port=8081

spring.ai.model.embedding=zhipuai
spring.ai.zhipuai.embedding.base-url=https://open.bigmodel.cn/api/paas
spring.ai.zhipuai.api-key=45dbdc07365a41e2bc032a96b159631e.cjhVhHQ8xV14YTxX
spring.ai.zhipuai.embedding.options.model=embedding-2
spring.ai.zhipuai.chat.options.model=GLM-4.7-Flash