spring.application.name=SpringAIFirstAttempt

server.port=8080

# deepseek?????????
spring.ai.deepseek.base-url=https://api.deepseek.com/v1
spring.ai.deepseek.api-key=sk-db2325b982f24d94a8c7e254bcc81b0c
spring.ai.deepseek.chat.options.model=deepseek-chat
# ??0-2????????????
spring.ai.deepseek.chat.options.temperature=0.8