server:
  port: 8001
  servlet:
    # 解决返回model返回乱码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  ai:
    zhipuai:
      api-key: ${zhipu_key}
      base-url: "https://open.bigmodel.cn/api/paas/"
      chat:
        options:
          model: "glm-4.5"
      embedding:
        options:
          model: embedding-3 #使用嵌入模型的名称
          dimensions: 256 # 嵌入向量的维度
    # 配置mcp client 服务 调用 了 springai-alibaba-mcp-server 提供的mcp服务
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://127.0.0.1:8002 # mcp 服务地址
    # 向量数据库配置
    vectorstore:
      redis:
        initialize-schema: true # 启动时自动创建Redis向量索引结构（首次部署需要开启）
        prefix: rag_prefix # Redis键名前缀，用于区分不同应用的向量数据
        index: rag_index # Redis向量索引名称

  # 数据源配置
  data:
    redis:
      host: 82.156.107.128 # redis服务地址
      port: 6379
      password: 123456
  # http请求超时时间
  http:
    client:
      read-timeout: 100000